//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_AccountForBuyingTC
    {
        public string CustomerID { get; set; }
        public string AccountNo { get; set; }
        public string AccountTitle { get; set; }
        public string Currency { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
