//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCHEQUEISSUE
    {
        public string ChequeID { get; set; }
        public string WorkingAcctID { get; set; }
        public string ChequeType { get; set; }
        public string ChequeStatusID { get; set; }
        public string ChequeStatusDesc { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ChequeNoStart { get; set; }
        public Nullable<decimal> ChequeNoEnd { get; set; }
        public Nullable<decimal> NextTransCom { get; set; }
        public string Status { get; set; }
        public string ApprovedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ActiveFlag { get; set; }
        public string CustomerID { get; set; }
    }
}
