//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDOCUMETARYCOLLECTIONCHARGE
    {
        public long DocCollectChargeID { get; set; }
        public string DocCollectCode { get; set; }
        public string WaiveCharges { get; set; }
        public string Chargecode { get; set; }
        public string ChargeAcct { get; set; }
        public string ChargePeriod { get; set; }
        public string ChargeCcy { get; set; }
        public string ExchRate { get; set; }
        public Nullable<double> ChargeAmt { get; set; }
        public string PartyCharged { get; set; }
        public string OmortCharges { get; set; }
        public string AmtInLocalCCY { get; set; }
        public string AmtDRfromAcct { get; set; }
        public string ChargeStatus { get; set; }
        public string Chargecode1 { get; set; }
        public string ChargeAcct1 { get; set; }
        public string ChargePeriod1 { get; set; }
        public string ChargeCcy1 { get; set; }
        public string ExchRate1 { get; set; }
        public Nullable<double> ChargeAmt1 { get; set; }
        public string PartyCharged1 { get; set; }
        public string OmortCharges1 { get; set; }
        public string AmtInLocalCCY1 { get; set; }
        public string AmtDRfromAcct1 { get; set; }
        public string ChargeStatus1 { get; set; }
        public string Chargecode2 { get; set; }
        public string ChargeAcct2 { get; set; }
        public string ChargePeriod2 { get; set; }
        public string ChargeCcy2 { get; set; }
        public string ExchRate2 { get; set; }
        public Nullable<double> ChargeAmt2 { get; set; }
        public string PartyCharged2 { get; set; }
        public string OmortCharges2 { get; set; }
        public string AmtInLocalCCY2 { get; set; }
        public string AmtDRfromAcct2 { get; set; }
        public string ChargeStatus2 { get; set; }
        public string Chargecode3 { get; set; }
        public string ChargeAcct3 { get; set; }
        public string ChargePeriod3 { get; set; }
        public string ChargeCcy3 { get; set; }
        public string ExchRate3 { get; set; }
        public Nullable<double> ChargeAmt3 { get; set; }
        public string PartyCharged3 { get; set; }
        public string OmortCharges3 { get; set; }
        public string AmtInLocalCCY3 { get; set; }
        public string AmtDRfromAcct3 { get; set; }
        public string ChargeStatus3 { get; set; }
        public string Chargecode4 { get; set; }
        public string ChargeAcct4 { get; set; }
        public string ChargePeriod4 { get; set; }
        public string ChargeCcy4 { get; set; }
        public string ExchRate4 { get; set; }
        public Nullable<double> ChargeAmt4 { get; set; }
        public string PartyCharged4 { get; set; }
        public string OmortCharges4 { get; set; }
        public string AmtInLocalCCY4 { get; set; }
        public string AmtDRfromAcct4 { get; set; }
        public string ChargeStatus4 { get; set; }
        public string Chargecode5 { get; set; }
        public string ChargeAcct5 { get; set; }
        public string ChargePeriod5 { get; set; }
        public string ChargeCcy5 { get; set; }
        public string ExchRate5 { get; set; }
        public Nullable<double> ChargeAmt5 { get; set; }
        public string PartyCharged5 { get; set; }
        public string OmortCharges5 { get; set; }
        public string AmtInLocalCCY5 { get; set; }
        public string AmtDRfromAcct5 { get; set; }
        public string ChargeStatus5 { get; set; }
        public string ChargeRemarks { get; set; }
        public string VATNo { get; set; }
        public string TaxCode { get; set; }
        public string TaxCcy { get; set; }
        public string TaxAmt { get; set; }
        public string TaxinLCCYAmt { get; set; }
        public string TaxDate { get; set; }
        public string Rowchages { get; set; }
        public Nullable<int> ViewType { get; set; }
    }
}
