//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIMPORT_NORMAILLC
    {
        public long Id { get; set; }
        public string NormalLCCode { get; set; }
        public string LCType { get; set; }
        public string ApplicantId { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantAddr1 { get; set; }
        public string ApplicantAddr2 { get; set; }
        public string ApplicantAddr3 { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Amount_Old { get; set; }
        public Nullable<double> CrTolerance { get; set; }
        public Nullable<double> DrTolerance { get; set; }
        public Nullable<System.DateTime> IssuingDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ExpiryPlace { get; set; }
        public Nullable<System.DateTime> ContingentExpiry { get; set; }
        public string AccountOfficer { get; set; }
        public string ContactNo { get; set; }
        public string BeneficiaryType { get; set; }
        public string BeneficiaryNo { get; set; }
        public string BeneficiaryName { get; set; }
        public string BeneficiaryAddr1 { get; set; }
        public string BeneficiaryAddr2 { get; set; }
        public string BeneficiaryAddr3 { get; set; }
        public string AdviseBankType { get; set; }
        public string AdviseBankNo { get; set; }
        public string AdviseBankName { get; set; }
        public string AdviseBankAddr1 { get; set; }
        public string AdviseBankAddr2 { get; set; }
        public string AdviseBankAddr3 { get; set; }
        public string ReimbBankType { get; set; }
        public string ReimbBankNo { get; set; }
        public string ReimbBankName { get; set; }
        public string ReimbBankAddr1 { get; set; }
        public string ReimbBankAddr2 { get; set; }
        public string ReimbBankAddr3 { get; set; }
        public string AdviseThruType { get; set; }
        public string AdviseThruNo { get; set; }
        public string AdviseThruName { get; set; }
        public string AdviseThruAddr1 { get; set; }
        public string AdviseThruAddr2 { get; set; }
        public string AdviseThruAddr3 { get; set; }
        public string AvailWithType { get; set; }
        public string AvailWithNo { get; set; }
        public string AvailWithName { get; set; }
        public string AvailWithAddr1 { get; set; }
        public string AvailWithAddr2 { get; set; }
        public string AvailWithAddr3 { get; set; }
        public string Commodity { get; set; }
        public Nullable<double> Prov { get; set; }
        public Nullable<double> LCAmountSecured { get; set; }
        public Nullable<double> LCAmountUnSecured { get; set; }
        public Nullable<double> LoanPrincipal { get; set; }
        public string Status { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string Amend_Status { get; set; }
        public string Cancel_Status { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public string AcceptRemarks { get; set; }
        public string Accept_Status { get; set; }
        public string AcceptBy { get; set; }
        public Nullable<System.DateTime> AcceptByDate { get; set; }
        public Nullable<int> PaymentFullFlag { get; set; }
        public Nullable<double> B4_AUT_Amount { get; set; }
        public Nullable<System.DateTime> CancelLCDate { get; set; }
        public Nullable<System.DateTime> ContingentExpiryDate { get; set; }
        public string CancelRemark { get; set; }
        public string CloseStatus { get; set; }
        public string CloseBy { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CloseApproveBy { get; set; }
        public Nullable<System.DateTime> CloseApproveDate { get; set; }
        public string CloseGenerateDelivery { get; set; }
        public string CloseExternalReference { get; set; }
        public string CloseRemark { get; set; }
    }
}
