//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNEWNORMALLOAN
    {
        public string Code { get; set; }
        public string MainCategory { get; set; }
        public string MainCategoryName { get; set; }
        public string SubCategory { get; set; }
        public string SubCategoryName { get; set; }
        public string PurpostCode { get; set; }
        public string PurpostName { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string LoanGroup { get; set; }
        public string LoanGroupName { get; set; }
        public string Currency { get; set; }
        public string BusDayDef { get; set; }
        public string BusDayDefName { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> ApproveAmount { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> Drawdown { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public string CreditAccount { get; set; }
        public string CommitmentID { get; set; }
        public string LimitReference { get; set; }
        public string RateType { get; set; }
        public string InterestBasic { get; set; }
        public string AnnuityRepMet { get; set; }
        public string IntPayMethod { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public string InterestKey { get; set; }
        public string IntSpread { get; set; }
        public string AutoSch { get; set; }
        public string DefineSch { get; set; }
        public string RepaySchType { get; set; }
        public string LoanStatus { get; set; }
        public Nullable<decimal> TotalInterestAmt { get; set; }
        public string PDStatus { get; set; }
        public string PrinRepAccount { get; set; }
        public string IntRepAccount { get; set; }
        public string ChrgRepAccount { get; set; }
        public Nullable<decimal> ExpectedLoss { get; set; }
        public Nullable<decimal> LossGivenDef { get; set; }
        public string CustomerRemarks { get; set; }
        public string AccountOfficer { get; set; }
        public string AccountOfficerName { get; set; }
        public string Secured { get; set; }
        public string CollateralID { get; set; }
        public Nullable<decimal> AmountAlloc { get; set; }
        public string CountryRisk { get; set; }
        public Nullable<decimal> LegacyRef { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> AmendedBy { get; set; }
        public Nullable<System.DateTime> Amend_UpdatedDate { get; set; }
        public Nullable<long> Amend_AuthorizedBy { get; set; }
        public Nullable<System.DateTime> Amend_AuthorizedDate { get; set; }
        public string Amend_Status { get; set; }
    }
}
