//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOPENACCOUNT_INTEREST
    {
        public long ID { get; set; }
        public long AccountID { get; set; }
        public string AccountCode { get; set; }
        public string CustomerType { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CategoryID { get; set; }
        public string Currency { get; set; }
        public string AccountTitle { get; set; }
        public Nullable<decimal> WorkingAmount { get; set; }
        public System.DateTime ValueDate { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
    }
}
