CREATE TABLE [dbo].[BEXPORT_LC_DOCS_PROCESSING](
	[DocCode] [nvarchar](50) NOT NULL,
	[BeneficiaryName] [nvarchar](50) NULL,
	[BeneficiaryAddr1] [nvarchar](50) NULL,
	[BeneficiaryAddr2] [nvarchar](50) NULL,
	[BeneficiaryAddr3] [nvarchar](50) NULL,
	[ApplicantName] [nvarchar](50) NULL,
	[ApplicantAddr1] [nvarchar](50) NULL,
	[ApplicantAddr2] [nvarchar](50) NULL,
	[ApplicantAddr3] [nvarchar](50) NULL,
	[IssuingBankNo] [nvarchar](50) NULL,
	[IssuingBankName] [nvarchar](50) NULL,
	[IssuingBankAddr1] [nvarchar](50) NULL,
	[IssuingBankAddr2] [nvarchar](50) NULL,
	[IssuingBankAddr3] [nvarchar](50) NULL,
	[NostroAgentBankNo] [nvarchar](50) NULL,
	[NostroAgentBankName] [nvarchar](50) NULL,
	[NostroAgentBankAddr1] [nvarchar](50) NULL,
	[NostroAgentBankAddr2] [nvarchar](50) NULL,
	[NostroAgentBankAddr3] [nvarchar](50) NULL,
	[ReceivingBankName] [nvarchar](50) NULL,
	[ReceivingBankAddr1] [nvarchar](50) NULL,
	[ReceivingBankAddr2] [nvarchar](50) NULL,
	[ReceivingBankAddr3] [nvarchar](50) NULL,
	[DocumentaryCreditNo] [nvarchar](50) NULL,
	[Commodity] [nvarchar](50) NULL,
	[Currency] [varchar](3) NULL,
	[Amount] [float] NULL,
	[DocumentReceivedDate] [date] NULL,
	[ProccessingDate] [date] NULL,
	[Tenor] [nvarchar](50) NULL,
	[InvoiceNo] [nvarchar](50) NULL,
	[DocsCode1] [nvarchar](50) NULL,
	[NoOfOriginals1] [int] NULL,
	[NoOfCopies1] [int] NULL,
	[DocsCode2] [nvarchar](50) NULL,
	[NoOfOriginals2] [int] NULL,
	[NoOfCopies2] [int] NULL,
	[DocsCode3] [nvarchar](50) NULL,
	[NoOfOriginals3] [int] NULL,
	[NoOfCopies3] [int] NULL,
	[Remark] [nvarchar](100) NULL,
	[SettlementInstruction] [nvarchar](100) NULL,
	[WaiveCharges] [nvarchar](3) NULL,
	[ChargeRemarks] [nvarchar](100) NULL,
	[VATNo] [nvarchar](50) NULL,
	[PaymentFull] [bit] NULL,
	[Status] [nvarchar](50) NULL,
	[CreateBy] [nvarchar](50) NULL,
	[CreateDate] [datetime] NULL,
	[UpdatedBy] [nvarchar](50) NULL,
	[UpdateDate] [datetime] NULL,
	[AuthorizedBy] [nvarchar](50) NULL,
	[AuthorizedDate] [datetime] NULL,
	[AmendStatus] [nvarchar](50) NULL,
	[AmendBy] [nvarchar](50) NULL,
	[AmendDate] [datetime] NULL,
	[AmendNo] [nvarchar](50) NOT NULL,
	[AmendNoOriginal] [nvarchar](50) NULL,
	[ActiveRecordFlag] [nvarchar](3) NULL,
	[RejectStatus] [nvarchar](50) NULL,
	[RejectDate] [datetime] NULL,
	[AcceptStatus] [nvarchar](50) NULL,
	[AcceptDate] [datetime] NULL,
 CONSTRAINT [PK_BEXPORT_LC_DOCS_PROCESSING] PRIMARY KEY CLUSTERED 
(
	[AmendNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


