CREATE TABLE [dbo].[BEXPORT_LC_AMEND](
	[AmendNo] [nvarchar](50) NOT NULL,
	[ImportLCCode] [nvarchar](50) NULL,
	[SenderReference] [nvarchar](50) NULL,
	[ReceiverReference] [nvarchar](50) NULL,
	[IssuingBankReference] [nvarchar](50) NULL,
	[IssuingBankType] [nvarchar](2) NULL,
	[IssuingBankNo] [nvarchar](50) NULL,
	[IssuingBankName] [nvarchar](200) NULL,
	[IssuingBankAddr1] [nvarchar](200) NULL,
	[IssuingBankAddr2] [nvarchar](200) NULL,
	[IssuingBankAddr3] [nvarchar](200) NULL,
	[DateOfIssue] [date] NULL,
	[DateOfAmendment] [date] NULL,
	[NumberOfAmendment] [int] NULL,
	[BeneficiaryNo] [nvarchar](50) NULL,
	[BeneficiaryName] [nvarchar](200) NULL,
	[BeneficiaryAddr1] [nvarchar](200) NULL,
	[BeneficiaryAddr2] [nvarchar](200) NULL,
	[BeneficiaryAddr3] [nvarchar](200) NULL,
	[NewDateOfExpiry] [date] NULL,
	[IncreaseOfDocumentaryCreditAmount] [float] NULL,
	[DecreaseOfDocumentaryCreditAmount] [float] NULL,
	[NewDocumentaryCreditAmountAfterAmendment] [float] NULL,
	[PercentageCreditAmountTolerance1] [float] NULL,
	[PercentageCreditAmountTolerance2] [float] NULL,
	[PlaceOfTakingInCharge] [nvarchar](200) NULL,
	[PortOfLoading] [nvarchar](200) NULL,
	[PortOfDischarge] [nvarchar](200) NULL,
	[PlaceOfFinalDestination] [nvarchar](200) NULL,
	[LatesDateOfShipment] [date] NULL,
	[Narrative] [nvarchar](1000) NULL,
	[SenderToReceiverInformation] [nvarchar](1000) NULL,
	[WaiveCharges] [nvarchar](3) NULL,
	[ChargeRemarks] [nvarchar](100) NULL,
	[VATNo] [nvarchar](50) NULL,
	[AmendStatus] [nvarchar](50) NULL,
	[AmendBy] [nvarchar](50) NULL,
	[AmendDate] [datetime] NULL,
	[RefAmendNo] [nvarchar](50) NULL,
 CONSTRAINT [PK_BEXPORT_LC_AMEND_1] PRIMARY KEY CLUSTERED 
(
	[AmendNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

