//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_CustomerSignature
    {
        public string CustomerId { get; set; }
        public string Signatures { get; set; }
        public string Status { get; set; }
        public string UserCreate { get; set; }
        public System.DateTime DateTimeCreate { get; set; }
        public string UserApprove { get; set; }
        public Nullable<System.DateTime> DateTimeApprove { get; set; }
        public string SignaturesNew { get; set; }
    }
}
