//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCOLLECTCHARGESFROMACCOUNT
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string AccountType { get; set; }
        public string CustomerAccount { get; set; }
        public string AccountCode { get; set; }
        public Nullable<decimal> ChargAmountLCY { get; set; }
        public Nullable<decimal> ChargAmountFCY { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string CategoryPLCode { get; set; }
        public string CategoryPLName { get; set; }
        public Nullable<decimal> DealRate { get; set; }
        public Nullable<decimal> VatAmountLCY { get; set; }
        public Nullable<decimal> VatAmountFCY { get; set; }
        public Nullable<decimal> TotalAmountLCY { get; set; }
        public Nullable<decimal> TotalAmountFCY { get; set; }
        public string VatSerialNo { get; set; }
        public string Narrative { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string Status { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Currency { get; set; }
    }
}
