//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCOMMITMENT_CONTRACT
    {
        public string ID { get; set; }
        public string Status { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string CustomerID { get; set; }
        public string GBFullName { get; set; }
        public string DocType { get; set; }
        public string DocID { get; set; }
        public string DocIssuePlace { get; set; }
        public Nullable<System.DateTime> DocIssueDate { get; set; }
        public Nullable<System.DateTime> DocExpiryDate { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyDescription { get; set; }
        public string CommitmentAmt { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CommitmentFeeStart { get; set; }
        public string CommitmentFeeEnd { get; set; }
        public string AvailableAmt { get; set; }
        public string TrancheAmt { get; set; }
        public Nullable<System.DateTime> DDStartDate { get; set; }
        public Nullable<System.DateTime> DDEndDate { get; set; }
        public string InterestedRepayAcct { get; set; }
        public string Secured { get; set; }
        public string CustomerRemark { get; set; }
        public string AccountOfficer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ActiveFlag { get; set; }
        public string ApproveUser { get; set; }
        public string InterestedRepayAcctName { get; set; }
        public string AccountOfficerID { get; set; }
    }
}
