//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINCOMINGCOLLECTIONPAYMENTCHARGE
    {
        public long Id { get; set; }
        public string CollectionPaymentCode { get; set; }
        public string WaiveCharges { get; set; }
        public string Chargecode { get; set; }
        public string ChargeAcct { get; set; }
        public string ChargePeriod { get; set; }
        public string ChargeCcy { get; set; }
        public string ExchRate { get; set; }
        public Nullable<double> ChargeAmt { get; set; }
        public string PartyCharged { get; set; }
        public string OmortCharges { get; set; }
        public string AmtInLocalCCY { get; set; }
        public string AmtDRfromAcct { get; set; }
        public string ChargeStatus { get; set; }
        public string ChargeRemarks { get; set; }
        public string VATNo { get; set; }
        public string TaxCode { get; set; }
        public string TaxCcy { get; set; }
        public string TaxAmt { get; set; }
        public string TaxinLCCYAmt { get; set; }
        public string TaxDate { get; set; }
        public string Rowchages { get; set; }
        public Nullable<double> ChargeAmtFCY { get; set; }
    }
}
