//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOANWORKINGACCOUNT
    {
        public string ID { get; set; }
        public string CustomerID { get; set; }
        public string GBFullName { get; set; }
        public string DocType { get; set; }
        public string DocID { get; set; }
        public string DocIssuePlace { get; set; }
        public Nullable<System.DateTime> DocIssueDate { get; set; }
        public Nullable<System.DateTime> DocExpiryDate { get; set; }
        public string CategoryCode { get; set; }
        public string Categoryname { get; set; }
        public string CategoryType { get; set; }
        public string AccountName { get; set; }
        public string ShortTittle { get; set; }
        public string Mnemonic { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyDescription { get; set; }
        public string ProductLineCode { get; set; }
        public string ProductLineDescription { get; set; }
        public string ProductLineType { get; set; }
        public string AlternateAccount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string ActiveFlag { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ActualBallance { get; set; }
        public Nullable<decimal> ClearedBallance { get; set; }
        public Nullable<decimal> WorkingAmount { get; set; }
    }
}
