//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOUTGOINGCOLLECTIONPAYMENTMT910
    {
        public System.Guid Id { get; set; }
        public string PaymentId { get; set; }
        public string TransactionReferenceNumber { get; set; }
        public string RelatedReference { get; set; }
        public string AccountIndentification { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string OrderingInstitutionName { get; set; }
        public string OrderingInstitutionAddress1 { get; set; }
        public string OrderingInstitutionAddress2 { get; set; }
        public string OrderingInstitutionAddress3 { get; set; }
        public string IntermediaryName { get; set; }
        public string IntermediaryAddress1 { get; set; }
        public string IntermediaryAddress2 { get; set; }
        public string IntermediaryAddress3 { get; set; }
        public string SendMessage { get; set; }
    }
}
