//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPRODUCTTYPE
    {
        public string ProductCode { get; set; }
        public string SavingFunctionType { get; set; }
        public string Description { get; set; }
        public string MaturityInstr { get; set; }
    }
}
