//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIMPORT_NORMAILLC_MT740
    {
        public long Id { get; set; }
        public string NormalLCCode { get; set; }
        public string GenerateMT740 { get; set; }
        public string ReceivingBank { get; set; }
        public string DocumentaryCreditNumber { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public string PlaceExpiry { get; set; }
        public string BeneficiaryType { get; set; }
        public string BeneficiaryNo { get; set; }
        public string BeneficiaryName { get; set; }
        public string BeneficiaryAddr1 { get; set; }
        public string BeneficiaryAddr2 { get; set; }
        public string BeneficiaryAddr3 { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public string CreditCurrency { get; set; }
        public string AvailableWithType { get; set; }
        public string AvailableWithNo { get; set; }
        public string AvailableWithName { get; set; }
        public string AvailableWithAddr1 { get; set; }
        public string AvailableWithAddr2 { get; set; }
        public string AvailableWithAddr3 { get; set; }
        public string DraweeNo { get; set; }
        public string DraweeName { get; set; }
        public string DraweeAddr1 { get; set; }
        public string DraweeAddr2 { get; set; }
        public string DraweeAddr3 { get; set; }
        public string ReimbursingBankChanges { get; set; }
        public string ApplicableRule { get; set; }
        public Nullable<double> PercentageCreditAmountTolerance1 { get; set; }
        public Nullable<double> PercentageCreditAmountTolerance2 { get; set; }
        public string SenderToReceiverInformation1 { get; set; }
        public string SenderToReceiverInformation2 { get; set; }
        public string SenderToReceiverInformation3 { get; set; }
        public string SenderToReceiverInformation4 { get; set; }
        public string DraftsAt1 { get; set; }
        public string DraftsAt2 { get; set; }
    }
}
